# ci.yml
name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.6
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Format files
        run: flutter format lib/** --set-exit-if-changed
      - name: Analyze files
        run: flutter analyze .
      - name: Build the APK
        run: flutter build apk --release
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Upload apk artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Upload ipa artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-ipa
          path: build/ios/iphoneos/app.ipa
